USE EMPLOYEE_MANAGEMENT;

SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;

SELECT * FROM PERFORMANCE;

-- Q1.Count total employees
SELECT COUNT(EMPLOYEE_ID) AS TOTAL_COUNT FROM EMPLOYEES;

-- Q2Count male and female employees
SELECT GENDER,COUNT(EMPLOYEE_ID) AS TOTAL_COUNT FROM EMPLOYEES GROUP BY GENDER;

-- Q3.Average age of employees
SELECT AVG(AGE) AS AVERAGE_AGE FROM EMPLOYEES;

-- Q4.Highest salary
SELECT MAX(SALARY) AS HIGHEST_SALARY FROM EMPLOYEES;

-- Q5.Lowest salary
SELECT MIN(SALARY) AS LOWEST_SALARY FROM EMPLOYEES;

-- Q6.Employees list by salary (highest to lowest)
SELECT EMPLOYEE_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

-- Q7.Total departments count
SELECT COUNT(DEPARTMENT_ID) AS TOTAL_DEPARTMENTS FROM DEPARTMENTS;

-- Q8.Employees count in each department
SELECT DEPARTMENT_ID,COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

# AGGREGATIONS

-- Q9.Average salary in each department
SELECT DEPARTMENT_ID,AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- Q10.Total salary paid in each department
SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- Q11.Highest salary in each department
SELECT DEPARTMENT_ID,MAX(SALARY) AS HIGHEST_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- Q12.Lowest salary in each department
SELECT DEPARTMENT_ID,MIN(SALARY) AS LOWEST_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- Q13.Average performance score
SELECT AVG(PERFORMANCE_SCORE) AS AVERAGE_PERFORMANCE_SCORE FROM PERFORMANCE;

# JOINS

-- Q14.Employee names along with their department names
SELECT EMPLOYEE_NAME,DEPARTMENT_NAME FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

-- Q15.Employee names along with their performance score and bonus
SELECT EMPLOYEE_NAME,PERFORMANCE_SCORE,BONUS FROM EMPLOYEES INNER JOIN PERFORMANCE ON EMPLOYEES.EMPLOYEE_ID=PERFORMANCE.EMPLOYEE_ID;

-- Q16.Show : Employee_Name,Department_Name,Performance_Score,Bonus
SELECT EMPLOYEE_NAME,
	DEPARTMENT_NAME,
    PERFORMANCE_SCORE,
    BONUS
FROM DEPARTMENTS 
INNER JOIN EMPLOYEES 
ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID 
INNER JOIN PERFORMANCE 
ON EMPLOYEES.EMPLOYEE_ID=PERFORMANCE.EMPLOYEE_ID;

# CASE

-- Q17.Classify salary
SELECT EMPLOYEE_ID,
EMPLOYEE_NAME,SALARY,
CASE
	WHEN SALARY>=60000 THEN 'HIGH'
	WHEN SALARY>=45000 THEN 'MEDIUM'
	ELSE 'LOW'
END AS CATEGORY
FROM EMPLOYEES;

-- Q18.Classify performance
SELECT EMPLOYEE_ID,
	PERFORMANCE_SCORE,
	CASE
		WHEN PERFORMANCE_SCORE>=90 THEN 'EXCELLENT'
		WHEN PERFORMANCE_SCORE>=80 THEN 'GOOD'
		WHEN PERFORMANCE_SCORE>=70 THEN 'AVERAGE'
		ELSE 'NEEDS IMPROVEMENT'
END AS RATING
FROM PERFORMANCE;

-- Q19.Bonus eligibility
SELECT BONUS,
CASE
	WHEN BONUS>=15000 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS BONUS_STATUS
FROM PERFORMANCE;

-- Q20.Employees hired after 2022-12-31
SELECT EMPLOYEE_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>'2022-12-31';

# Subqueries

-- Q21.Employees earning above the average salary
SELECT EMPLOYEE_NAME,SALARY FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

-- Q22.Employees with above-average performance scores
SELECT EMPLOYEE_NAME,PERFORMANCE_SCORE FROM EMPLOYEES INNER JOIN PERFORMANCE ON EMPLOYEES.EMPLOYEE_ID=PERFORMANCE.EMPLOYEE_ID WHERE PERFORMANCE_SCORE>(SELECT AVG(PERFORMANCE_SCORE) FROM PERFORMANCE);

-- Q23.Highest-paid employee
SELECT EMPLOYEE_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 1;

-- Q24.Employee with the highest performance score
SELECT EMPLOYEE_NAME,PERFORMANCE_SCORE FROM EMPLOYEES INNER JOIN PERFORMANCE ON EMPLOYEES.EMPLOYEE_ID=PERFORMANCE.EMPLOYEE_ID ORDER BY PERFORMANCE_SCORE DESC LIMIT 1;

# CTE

-- Q25.CTE to calculate the average salary and display employees earning above that average
WITH AVG_SALARY AS
(
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES
)
SELECT EMPLOYEE_ID,
	EMPLOYEE_NAME,
    SALARY FROM EMPLOYEES
WHERE SALARY>(SELECT AVERAGE_SALARY FROM AVG_SALARY); 


# WINDOW FUNCTIONS

-- Q26.Rank employees by salary
SELECT EMPLOYEE_NAME,
SALARY,
RANK() OVER(ORDER BY SALARY DESC
) AS EMPLOYEE_RANK
FROM EMPLOYEES;

-- Q27.Top 3 highest-paid employees
WITH HIGH_PAID AS
(
SELECT EMPLOYEE_NAME,
SALARY,
RANK() OVER(ORDER BY SALARY DESC
) AS EMPLOYEE_SALARY_RANK
FROM EMPLOYEES
)
SELECT * FROM HIGH_PAID WHERE EMPLOYEE_SALARY_RANK<=3;

-- Q28.Assign row numbers based on salary
WITH EMPLOYEE_SALARY AS
(
SELECT EMPLOYEE_NAME,SALARY,
ROW_NUMBER() OVER(ORDER BY SALARY DESC
) AS SALARY_ROW_N
FROM EMPLOYEES
)
SELECT * FROM EMPLOYEE_SALARY;

-- Q29.Previous employee's salary using LAG()
WITH EMPLOYEE_SALARY AS
(
SELECT EMPLOYEE_NAME,SALARY,
LAG(SALARY) OVER(ORDER BY SALARY DESC
) AS PREVIOUS_SALARY
FROM EMPLOYEES
)
SELECT * FROM EMPLOYEE_SALARY;

-- Q30.Next employee's salary using LEAD()
WITH EMPLOYEE_SALARY AS
(
SELECT EMPLOYEE_NAME,SALARY,
LEAD(SALARY) OVER(ORDER BY SALARY DESC
) AS NEXT_SALARY
FROM EMPLOYEES
)
SELECT * FROM EMPLOYEE_SALARY;

-- Q31.Highest-paid employee in each department using a window function.
WITH EMP_SAL AS
(
SELECT EMPLOYEE_NAME,DEPARTMENT_NAME,SALARY,
RANK() OVER(PARTITION BY DEPARTMENT_NAME ORDER BY SALARY DESC
) AS HIGH_PAID
FROM DEPARTMENTS INNER JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID
)
SELECT * FROM EMP_SAL WHERE HIGH_PAID=1;


-- Business Questions
